spring:
  messages:
    basename: i18n.login

  datasource:
    url: jdbc:mysql://localhost:3306/npulibrary?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      #更新或创建数据表
      ddl-auto: update
    show-sql: true